### ISSUE TITLE
Possible bug for C# Flex Consumption TimeTrigger Functions?

### ISSUE THREAD

**Issue by plamber** [Azure-Samples/azure-functions-flex-consumption-samples#37]
### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
We have observed that scheduled functions do not behave as expected when configured to run on startup. Specifically, if configured as shown in the example below, these functions will trigger twice during the timer sequence but will not trigger after deployment.
```
public async Task RunAsync([TimerTrigger("YourSchedule", RunOnStartup = true)] TimerInfo myTimer, ILogger log)
```

Let us imagine you configure the trigger to run every 6 hours. We observed that every 6 hours it runs twice.

### Expected/desired behavior
The function should trigger after deployment and not when the TimerTrigger is scheduled to run twice.

### OS and Version?
Latest Azure Function SDK. C#

**Comment by mathewc** [comment]
@plamber Our documentation [here](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-timer?tabs=python-v2%2Cisolated-process%2Cnodejs-v4&pivots=programming-language-csharp#attributes) cautions against the use of RunOnStartup, because the behavior can be confusing. What are you trying to accomplish exactly? Can you provide an invocation ID and timestamp for a time when you saw the issue, and we can look at the platform logs?

**Comment by plamber** [comment]
Hi @mathewc,
to be honest I missed that information. We used it in the past in our Azure Functions on an app service that is configured for always running. Therefore, we were used to have these function running after deploying the Azure Function to the app service.

Now I understand that this shouldn't be used at all.

Thank you. I am going to close the issue.

Cheers
